(part "AQW614"
    (packageRef "DIP762W47P254L978H410Q8N")
    (interface
        (port "1" (symbPinId 1) (portName "A1") (portType INOUT))
        (port "2" (symbPinId 2) (portName "K1") (portType INOUT))
        (port "3" (symbPinId 3) (portName "A2") (portType INOUT))
        (port "4" (symbPinId 4) (portName "K2") (portType INOUT))
        (port "5" (symbPinId 5) (portName "D1") (portType INOUT))
        (port "6" (symbPinId 6) (portName "D2") (portType INOUT))
        (port "7" (symbPinId 7) (portName "D3") (portType INOUT))
        (port "8" (symbPinId 8) (portName "D4") (portType INOUT))
    )
    (partClass UNDEF)
    (useInSchema Y)
    (useInLayout Y)
    (inPartsList Y)
    (partType NORMAL)
    (placeRestriction FREE)
    (property "compKind" "161")
    (property "Manufacturer_Name" "Panasonic")
    (property "Manufacturer_Part_Number" "AQW614")
    (property "Mouser_Part_Number" "769-AQW614")
    (property "Mouser_Price/Stock" "https://www.mouser.co.uk/ProductDetail/Panasonic/AQW614?qs=sEN%2FkO1EG6aIbQazZO7uDw%3D%3D")
    (property "Arrow_Part_Number" "")
    (property "Arrow_Price/Stock" "")
    (property "Description" "Panasonic 0.1 A Solid State Relay, PCB Mount, MOSFET, 400 V Maximum Load")
    (property "Datasheet_Link" "https://industry.panasonic.com/ac/cdn/e/control/relay/photomos/catalog/semi_eng_gu1a1b_aqw61.pdf")
    (property "symbolName1" "AQW614")
)
