(part "SQ4917CEY-T1_GE3"
    (packageRef "SOIC127P600X175-8N")
    (interface
        (port "1" (symbPinId 1) (portName "S1") (portType INOUT))
        (port "2" (symbPinId 2) (portName "G1") (portType INOUT))
        (port "3" (symbPinId 3) (portName "S2") (portType INOUT))
        (port "4" (symbPinId 4) (portName "G2") (portType INOUT))
        (port "5" (symbPinId 5) (portName "D2_1") (portType INOUT))
        (port "6" (symbPinId 6) (portName "D2_2") (portType INOUT))
        (port "7" (symbPinId 7) (portName "D1_1") (portType INOUT))
        (port "8" (symbPinId 8) (portName "D1_2") (portType INOUT))
    )
    (partClass UNDEF)
    (useInSchema Y)
    (useInLayout Y)
    (inPartsList Y)
    (partType NORMAL)
    (placeRestriction FREE)
    (property "compKind" "221")
    (property "Manufacturer_Name" "Vishay")
    (property "Manufacturer_Part_Number" "SQ4917CEY-T1_GE3")
    (property "Mouser_Part_Number" "78-SQ4917CEY-T1_GE3")
    (property "Mouser_Price/Stock" "https://www.mouser.co.uk/ProductDetail/Vishay-Semiconductors/SQ4917CEY-T1_GE3?qs=Y0Uzf4wQF3m%252Bt%252BVrseINGQ%3D%3D")
    (property "Arrow_Part_Number" "")
    (property "Arrow_Price/Stock" "")
    (property "Description" "MOSFET Automotive Dual P-Channel 60V 175CmOSFET 48mO 10V, 61.2mO 4.5V")
    (property "Datasheet_Link" "https://www.vishay.com/docs/62019/sq4917cey.pdf")
    (property "symbolName1" "SQ4917CEY-T1_GE3")
)
